name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run formatting check
      run: npm run format:check || echo "No format check script found"
    
    - name: Run tests
      run: npm test
    
    - name: Run test coverage
      run: npm run test:coverage || echo "No coverage script found"
    
    - name: Run security audit
      run: npm audit --audit-level=moderate || echo "Security audit failed"
    
    - name: Validate CLI entrypoint
      run: |
        # Test CLI binary exists and is executable
        test -f index.js
        test -x index.js || chmod +x index.js
        
        # Test basic CLI commands
        node index.js --help
        node index.js --version
        
        # Test with mock API key
        echo "GEMINI_API_KEY=test_key" > .env
        node index.js --analyze || echo "Analysis failed as expected without real API key"
    
    - name: Test package creation
      run: npm pack
    
    - name: Validate package contents
      run: |
        tar -tzf inteli-packs-*.tgz | head -20
        npm pack --dry-run
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.node-version }}
        path: |
          test-results/
          coverage/
          *.log
          inteli-packs-*.tgz

  security:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security scan
      run: |
        npm audit --audit-level=moderate
        npm audit fix --dry-run
    
    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.before }}
        head: ${{ github.sha }} 